#!/bin/bash
### This script aligns fastq files with bowtie2 and produces a text file with unmapped reads, a text file with depth information, ggplot of the depth and a csv file with low depth positions.
### This script requires an indexed reference genome and the Rscript plot_depth.R.

# Create a variable to store the reference path. Requires a previously created reference with bowtie2-build.
reference="/home/josemari/Desktop/Jose/Reference_sequences/MN908947"
# Create a variable to store the path for Rscripts.
Rscripts="/home/josemari/Desktop/Jose/General_scripts/R"
# Get the name of the fastq files and the episeq consensus.
rawfastq_tag="L22IRL12528_S33_L001"
Fw=${rawfastq_tag}"_R1_001.fastq.gz"
Rv=${rawfastq_tag}"_R2_001.fastq.gz"
episeq_cns=${rawfastq_tag}"_R_16069.consensus.fa"

#COMANDS
#Indexing
#bowtie2-build '$param.ref' sarscov
# Align the input file to the reference with bowtie2 and write out a txt documment with unnaligned reads.
echo Aligning ${rawfastq_tag} with bowtie2...
bowtie2 --un ${rawfastq_tag}_not_aligned.txt -x ${reference} -1 ${Fw} -2 ${Rv} -S ${rawfastq_tag}.sam
# Convert the sam to bam file and remove sam file.
echo Converting sam to bam file...
samtools view -b ${rawfastq_tag}.sam > ${rawfastq_tag}.bam
rm ${rawfastq_tag}.sam
# Sort the sam file and remove unsorted bam.
echo Sorting bam file...
samtools sort ${rawfastq_tag}.bam -o ${rawfastq_tag}_srtd.bam
rm ${rawfastq_tag}.bam
# Index the sorted bam file.
echo Indexing bam file...
samtools index ${rawfastq_tag}_srtd.bam
# Convert conensus fasq from bam file.
echo Making fastq consensus sequence...
samtools mpileup -uf ${reference}.fasta ${rawfastq_tag}_srtd.bam | bcftools call -c | vcfutils.pl vcf2fq > ${rawfastq_tag}_cns.fq
# Making consensus fasta from consensus fasq...
echo Getting consensus fasta... Bases quality lower than 20 set to N.
seqtk seq -aQ64 -q20 -n N ${rawfastq_tag}_cns.fq > ${rawfastq_tag}_cns.fasta

# Call the Rscript to find nt differences between the generated consensus and the episeq consensus.
echo "Calling find_nt_diff.R" 
Rscript ${Rscripts}/find_nt_diff.R ${rawfastq_tag}_cns.fasta ${episeq_cns}

# Get depth information to text file and remove bam files.
echo Getting depth from bam file...
samtools depth -a -H ${rawfastq_tag}_srtd.bam -o ${rawfastq_tag}_depth.txt

# Call Rscript for plotting.
Rscript $Rscripts/plot_depth_pairedend.R `pwd`/${rawfastq_tag}_depth.txt

# Move the plot and csv files generated by the Rscripts.
mkdir ${rawfastq_tag}_results
mv Alignment_changes.csv ${rawfastq_tag}_Alignment_changes.csv
mv ${rawfastq_tag}_not_aligned.txt ${rawfastq_tag}_depth.txt ${rawfastq_tag}_depth.pdf ${rawfastq_tag}_low_depth_positions.csv ${rawfastq_tag}_Alignment_changes.csv ${rawfastq_tag}_cns.fasta mafft_aligned.fasta ${rawfastq_tag}_results
# Remove unnecesary files.
rm ${rawfastq_tag}_srtd.bam ${rawfastq_tag}_srtd.bam.bai ${rawfastq_tag}_cns.fq fasta_to_align.fasta


